package com.pabhinav.zovido.pojo;

/**
 * @author pabhinav
 */
public enum ExceptionInferType {
    GOOGLE_CREDENTIAL_EXCEPTION, ZOVIDO_NO_INSTANCE, URL_EXCEPTION_WRONG_FILE_KEY, WRONG_FILE_KEY_OR_NO_FILE_PERMISSION, WORKSHEET_FEED_NULL, NO_WORKSHEET_IN_SPREADSHEET, NO_WORKSHEET_WITH_SPECIFIED_NAME_FOUND, NULL_LIST_FEED_URL_FROM_WORKSHEET, NO_EXCEPTION;
}
